'use strict';

const { BrainError, CODES } = require('../errors');

/**
 * Deterministic mock provider for CI and Phase 1 — no network, no keys.
 * @returns {import('../types').ProviderAdapter}
 */
function createMockAdapter(opts) {
  const options = opts || {};
  const latencyMs = typeof options.latencyMs === 'number' ? options.latencyMs : 1;

  return {
    id: 'mock',
    capabilities() {
      return new Set(['text', 'structured_json']);
    },
    async healthCheck() {
      return { ok: true, detail: 'mock' };
    },
    /**
     * @param {import('../types').GenerateRequest} req
     * @returns {Promise<import('../types').GenerateResult>}
     */
    async generate(req) {
      if (!req || !req.model) {
        throw new BrainError(CODES.bad_request, 'Mock adapter requires model');
      }
      if (req.model.provider !== 'mock') {
        throw new BrainError(CODES.bad_request, 'Mock adapter only serves provider=mock');
      }
      if (options.failWith) {
        throw options.failWith;
      }

      const started = Date.now();
      const lastUser = [...(req.messages || [])].reverse().find((m) => m.role === 'user');
      const userText = (lastUser && lastUser.content) || '';

      let text;
      let json;
      if (req.responseSchema) {
        json = buildStructuredMock(req.responseSchema, userText, options.structuredFixture);
        text = JSON.stringify(json);
      } else {
        text = options.textFixture != null
          ? String(options.textFixture)
          : 'MOCK:' + (userText ? userText.slice(0, 200) : 'ok');
      }

      const waited = Date.now() - started;
      if (latencyMs > waited) {
        // keep deterministic & fast in tests
      }

      const inputTokens = Math.max(1, Math.ceil(JSON.stringify(req.messages || []).length / 4));
      const outputTokens = Math.max(1, Math.ceil(String(text).length / 4));

      return {
        text,
        json,
        usage: { inputTokens, outputTokens, cachedTokens: 0 },
        providerRequestId: 'mock-' + (req.correlationId || 'local'),
        latencyMs: Math.max(latencyMs, waited),
        model: { provider: 'mock', model: req.model.model }
      };
    }
  };
}

/**
 * @param {object} schema
 * @param {string} userText
 * @param {unknown} [fixture]
 */
function buildStructuredMock(schema, userText, fixture) {
  if (fixture !== undefined) return fixture;
  if (!schema || typeof schema !== 'object') return { ok: true, text: userText || 'mock' };

  const s = /** @type {Record<string, unknown>} */ (schema);
  if (s.type === 'object' && s.properties && typeof s.properties === 'object') {
    const props = /** @type {Record<string, unknown>} */ (s.properties);
    /** @type {Record<string, unknown>} */
    const out = {};
    for (const [key, sub] of Object.entries(props)) {
      out[key] = mockValueForSchema(/** @type {object} */ (sub), key, userText);
    }
    if (Array.isArray(s.required)) {
      for (const key of s.required) {
        if (!(String(key) in out)) out[String(key)] = 'mock';
      }
    }
    return out;
  }
  return { value: userText || 'mock' };
}

/**
 * @param {object} schema
 * @param {string} key
 * @param {string} userText
 */
function mockValueForSchema(schema, key, userText) {
  if (!schema || typeof schema !== 'object') return 'mock';
  const s = /** @type {Record<string, unknown>} */ (schema);
  if (Object.prototype.hasOwnProperty.call(s, 'const')) return s.const;
  if (s.type === 'string') {
    if (key === 'bodyMarkdown') return '# Mock draft\n\n' + (userText || 'Generated by mock provider.');
    if (key === 'title') return 'Mock title';
    if (key === 'meta') return 'Mock meta description for SEO testing.';
    return 'mock-' + key;
  }
  if (s.type === 'number') return 1;
  if (s.type === 'boolean') return true;
  if (s.type === 'array') return [];
  if (s.type === 'object') return buildStructuredMock(s, userText);
  return 'mock';
}

module.exports = { createMockAdapter };
