'use strict';

const { BrainError, CODES } = require('../errors');

/**
 * Deterministic mock provider for CI and Phase 1 — no network, no keys.
 * @returns {import('../types').ProviderAdapter}
 */
function createMockAdapter(opts) {
  const options = opts || {};
  const latencyMs = typeof options.latencyMs === 'number' ? options.latencyMs : 1;

  return {
    id: 'mock',
    capabilities() {
      return new Set(['text', 'structured_json']);
    },
    async healthCheck() {
      return { ok: true, detail: 'mock' };
    },
    /**
     * @param {import('../types').GenerateRequest} req
     * @returns {Promise<import('../types').GenerateResult>}
     */
    async generate(req) {
      if (!req || !req.model) {
        throw new BrainError(CODES.bad_request, 'Mock adapter requires model');
      }
      if (req.model.provider !== 'mock') {
        throw new BrainError(CODES.bad_request, 'Mock adapter only serves provider=mock');
      }
      if (options.failWith) {
        throw options.failWith;
      }

      const started = Date.now();
      const lastUser = [...(req.messages || [])].reverse().find((m) => m.role === 'user');
      const userText = (lastUser && lastUser.content) || '';

      let text;
      let json;
      if (req.responseSchema) {
        json = buildStructuredMock(req.responseSchema, userText, options.structuredFixture);
        text = JSON.stringify(json);
      } else {
        text = options.textFixture != null
          ? String(options.textFixture)
          : 'MOCK:' + (userText ? userText.slice(0, 200) : 'ok');
      }

      const waited = Date.now() - started;
      if (latencyMs > waited) {
        // keep deterministic & fast in tests
      }

      const inputTokens = Math.max(1, Math.ceil(JSON.stringify(req.messages || []).length / 4));
      const outputTokens = Math.max(1, Math.ceil(String(text).length / 4));

      return {
        text,
        json,
        usage: { inputTokens, outputTokens, cachedTokens: 0 },
        providerRequestId: 'mock-' + (req.correlationId || 'local'),
        latencyMs: Math.max(latencyMs, waited),
        model: { provider: 'mock', model: req.model.model }
      };
    }
  };
}

/**
 * @param {object} schema
 * @param {string} userText
 * @param {unknown} [fixture]
 */
function buildStructuredMock(schema, userText, fixture) {
  if (fixture !== undefined) return fixture;
  if (!schema || typeof schema !== 'object') return { ok: true, text: userText || 'mock' };

  const s = /** @type {Record<string, unknown>} */ (schema);
  if (s.type === 'object' && s.properties && typeof s.properties === 'object') {
    const props = /** @type {Record<string, unknown>} */ (s.properties);
    /** @type {Record<string, unknown>} */
    const out = {};
    for (const [key, sub] of Object.entries(props)) {
      out[key] = mockValueForSchema(/** @type {object} */ (sub), key, userText);
    }
    if (Array.isArray(s.required)) {
      for (const key of s.required) {
        if (!(String(key) in out)) out[String(key)] = 'mock';
      }
    }
    return out;
  }
  return { value: userText || 'mock' };
}

/**
 * @param {object} schema
 * @param {string} key
 * @param {string} userText
 */
function mockValueForSchema(schema, key, userText) {
  if (!schema || typeof schema !== 'object') return 'mock';
  const s = /** @type {Record<string, unknown>} */ (schema);
  if (Object.prototype.hasOwnProperty.call(s, 'const')) return s.const;
  if (s.type === 'string') {
    if (key === 'bodyMarkdown') {
      return (
        'When you need local help, every hour of delay costs money. ' +
        (userText ? userText.slice(0, 120) : 'Our team') +
        ' delivers practical repairs and servicing for operators who rely on their equipment every day.\n\n' +
        '## Reliable local service\n\n' +
        'We diagnose faults carefully, explain what is required, and focus on getting plant and machinery ' +
        'operating safely again. Scheduled servicing helps catch wear before it becomes a roadside breakdown.\n\n' +
        '## Who we help\n\n' +
        'Civil contractors, owner-operators and local businesses use us for dependable mechanical work ' +
        'across the region. Generated by mock provider.'
      );
    }
    if (key === 'title') return 'Mock Service Repairs Canberra | Mock Biz';
    if (key === 'meta') {
      return 'Mock Biz provides service repairs and diesel diagnostics in Canberra for plant and heavy equipment.';
    }
    if (key === 'h1') return 'Mock Service Repairs Canberra';
    if (key === 'slug') return 'mock-service-repairs-canberra';
    if (key === 'primaryKeyword') return 'Mock Service Repairs Canberra';
    if (key === 'ctaHeadline') return 'Get in touch';
    if (key === 'ctaBody') {
      return 'Contact us to discuss your equipment, book a service, or ask about the next available slot.';
    }
    if (key === 'question') return 'How quickly can you look at my machine?';
    if (key === 'answer') {
      return 'We prioritise breakdowns where we can and will confirm the next available assessment when you call.';
    }
    if (key === 'pipe') return '#1f7bb8';
    if (key === 'hivis') return '#ff6a1f';
    if (key === 'steel') return '#1a2230';
    if (key === 'safety') return '#ffc400';
    if (key === 'lightBg') return '#eef2f6';
    if (key === 'presetName') return 'Mock Trade Theme';
    if (key === 'rationale' || key === 'changeNotes' || key === 'notes') {
      return 'Mock theme / ads suggestion for testing.';
    }
    if (key === 'campaignName') return 'Mock Local Leads';
    if (key === 'objective') return 'Drive calls and quote requests';
    if (key === 'geoFocus') return 'Canberra ACT';
    if (key === 'budgetNotes') return 'Start modest; scale winners.';
    if (key === 'path1') return 'quote';
    if (key === 'path2') return 'local';
    if (key === 'finalUrlHint') return '/';
    if (key === 'service') return 'Mock service';
    if (key === 'location') return 'Canberra';
    return 'mock-' + key;
  }
  if (s.type === 'number') return 1;
  if (s.type === 'boolean') return true;
  if (s.type === 'array') {
    if (key === 'faqs') {
      return [
        {
          question: 'How quickly can you look at my machine?',
          answer: 'We prioritise breakdowns where we can and will confirm the next available assessment when you call.'
        },
        {
          question: 'What equipment do you service?',
          answer: 'We work on a wide range of diesel-powered plant and construction equipment used on local sites.'
        }
      ];
    }
    if (key === 'secondaryKeywords') {
      return ['mock machinery repairs canberra', 'heavy equipment servicing canberra'];
    }
    if (key === 'headlines') {
      return [
        'Local Trade Experts',
        'Free Quote Today',
        'Same-Day Callouts',
        'Trusted Local Team',
        'Book Online Now'
      ];
    }
    if (key === 'descriptions') {
      return [
        'Licensed local trades for fast, fixed-price jobs. Call for a free quote today.',
        'Serving your suburb with clear pricing and tidy workmanship. Request a callback.'
      ];
    }
    if (key === 'keywords') {
      return ['plumber canberra', 'blocked drain canberra', 'emergency plumber'];
    }
    if (key === 'negatives') {
      return ['jobs', 'diy', 'course', 'training'];
    }
    if (key === 'landingPageHints') {
      return ['/', '/blocked-drains-canberra'];
    }
    if (key === 'adGroups') {
      return [
        { name: 'Core service', theme: 'Primary commercial keyword' },
        { name: 'Emergency', theme: 'Urgent / same-day intent' }
      ];
    }
    if (s.items) {
      return [mockValueForSchema(/** @type {object} */ (s.items), key.replace(/s$/, '') || 'item', userText)];
    }
    return [];
  }
  if (s.type === 'object') return buildStructuredMock(s, userText);
  return 'mock';
}

module.exports = { createMockAdapter };
