'use strict';

/**
 * Guardian — validates Recommendations and Execution Plans.
 * Blocks publish / live mutation. Validates Forge plans before Apply.
 */

const { getCapability, isExecutableCapability } = require('./capability-registry');
const { PLAN_STATUSES } = require('./execution-plan');

const PROTECTED_PATH_PATTERNS = [
  /form.*recipient/i,
  /leadRouting/i,
  /tracking/i,
  /gtm/i,
  /fbq/i,
  /domain/i,
  /billing/i,
  /permissions/i,
  /auth/i,
  /webhook/i
];

function validateRecommendation(rec, opts) {
  const o = opts || {};
  const critical = [];
  const warnings = [];
  const r = rec || {};

  if (!r.title || !String(r.title).trim()) {
    critical.push({ code: 'title_required', message: 'Recommendation title is required' });
  }
  if (!r.specialist) {
    critical.push({ code: 'specialist_required', message: 'Specialist id is required' });
  }
  if (r.publish === true || (r.proposedChange && r.proposedChange.publish === true)) {
    critical.push({ code: 'publish_forbidden', message: 'AI Team cannot publish' });
  }
  if (r.applyLive === true || (r.proposedChange && r.proposedChange.applyLive === true)) {
    critical.push({ code: 'live_mutation_forbidden', message: 'Live site mutation is forbidden' });
  }

  const change = r.proposedChange || r.proposed_change || {};
  const paths = []
    .concat(change.paths || [])
    .concat(change.configPaths || [])
    .concat(Array.isArray(r.affectedAreas) ? r.affectedAreas : r.affected_areas || []);

  // Atlas must not own config paths — warn if a recommendation smuggles them in.
  if ((change.paths && change.paths.length) || (change.configPaths && change.configPaths.length)) {
    warnings.push({
      code: 'atlas_config_paths',
      message: 'Recommendations should describe business outcomes; Forge owns config paths'
    });
  }

  for (const p of paths) {
    const s = String(p);
    if (PROTECTED_PATH_PATTERNS.some((re) => re.test(s))) {
      critical.push({
        code: 'protected_path',
        message: 'Protected path cannot be changed via AI Team: ' + s
      });
    }
  }

  if (r.executable === true) {
    const target = change.capabilityId || change.sectionKey || change.appId || change.outcome;
    const outcomeOk =
      target === 'strengthen_primary_cta' ||
      target === 'enable_faq_for_objections' ||
      isExecutableCapability(target);
    if (!target || !outcomeOk) {
      critical.push({
        code: 'not_executable',
        message: 'This outcome is not on the Forge allowlist yet.'
      });
    }
  }

  if (change.sectionKey || change.capabilityId) {
    const cap = getCapability(change.sectionKey || change.capabilityId);
    if (!cap && !r.capabilityGap && !r.capability_gap && change.type !== 'outcome') {
      warnings.push({
        code: 'unknown_capability',
        message: 'Target capability is not on the real Marketplace allowlist — mark as capability_gap'
      });
    }
  }

  if (o.requireTenantSiteId && r.siteId && r.siteId !== o.requireTenantSiteId) {
    critical.push({ code: 'tenant_mismatch', message: 'Recommendation siteId mismatch' });
  }

  return {
    ok: critical.length === 0,
    critical,
    warnings
  };
}

/**
 * Guardian gate before Forge may produce/apply configuration mutations.
 */
function validateExecutionPlan(plan, opts) {
  const o = opts || {};
  const critical = [];
  const warnings = [];
  const p = plan || {};

  if (!p.id) critical.push({ code: 'plan_id_required', message: 'Execution Plan id is required' });
  if (!p.generatedBy || p.generatedBy !== 'forge') {
    critical.push({
      code: 'forge_only',
      message: 'Execution Plans must be generated by Forge'
    });
  }
  if (p.publish === true) {
    critical.push({ code: 'publish_forbidden', message: 'Execution Plans cannot publish' });
  }
  if (!Array.isArray(p.steps)) {
    critical.push({ code: 'steps_required', message: 'Execution Plan steps array is required' });
  }

  const status = p.status || 'draft';
  if (PLAN_STATUSES.indexOf(status) < 0) {
    warnings.push({ code: 'unknown_status', message: 'Unknown plan status: ' + status });
  }

  const steps = Array.isArray(p.steps) ? p.steps : [];
  if (!steps.length) {
    // Knowledge-only plans are valid but not config-executable
    warnings.push({
      code: 'no_config_steps',
      message: 'Plan has no configuration steps — Site Knowledge or manual follow-up only'
    });
  }

  steps.forEach(function (step, idx) {
    if (!step || !step.operation) {
      critical.push({ code: 'step_operation', message: 'Step ' + (idx + 1) + ' needs an operation' });
      return;
    }
    const paths = step.configPaths || [];
    paths.forEach(function (path) {
      const s = String(path);
      if (PROTECTED_PATH_PATTERNS.some((re) => re.test(s))) {
        critical.push({
          code: 'protected_path',
          message: 'Protected path in step ' + (idx + 1) + ': ' + s
        });
      }
    });
    if (step.operation === 'hero_cta' || step.operation === 'sticky_cta' || step.operation === 'footer_cta') {
      const cta = step.after && step.after.cta != null ? String(step.after.cta).trim() : '';
      if (!cta) {
        critical.push({ code: 'cta_required', message: 'Step ' + (idx + 1) + ' CTA is empty' });
      } else if (/^(get in touch|contact us|learn more)$/i.test(cta)) {
        critical.push({
          code: 'cta_too_generic',
          message: 'Step ' + (idx + 1) + ' CTA is too generic'
        });
      }
    }
    if (step.operation === 'enable_faq' || step.operation === 'enable_section') {
      const key = step.operation === 'enable_faq' ? 'faq' : String((step.sectionKey || 'faq')).trim();
      if (!getCapability(key)) {
        critical.push({
          code: 'capability_not_allowlisted',
          message: 'Step ' + (idx + 1) + ' targets a non-allowlisted capability'
        });
      }
    }
    if (
      step.operation === 'create_landing_page' &&
      !(step.after && step.after.page && step.after.page.slug && step.after.page.title)
    ) {
      critical.push({
        code: 'landing_page_required',
        message: 'Step ' + (idx + 1) + ' needs a landing page title and slug'
      });
    }
  });

  if (!p.rollbackStrategy || !p.rollbackStrategy.type) {
    warnings.push({
      code: 'rollback_missing',
      message: 'Execution Plan should declare a rollback strategy'
    });
  }

  if (o.requireSiteId && p.siteId && p.siteId !== o.requireSiteId) {
    critical.push({ code: 'tenant_mismatch', message: 'Execution Plan siteId mismatch' });
  }

  return {
    ok: critical.length === 0,
    critical,
    warnings,
    canApply: critical.length === 0 && steps.length > 0
  };
}

function attachGuardian(rec) {
  const forced = { ...rec, executable: false };
  const result = validateRecommendation(forced);
  return {
    ...forced,
    guardian: result
  };
}

module.exports = {
  validateRecommendation,
  validateExecutionPlan,
  attachGuardian,
  PROTECTED_PATH_PATTERNS
};
