/**
 * Online Quote System — PDF generation (server-side, pdfkit).
 */

const PDFDocument = require('pdfkit');
const { formatMoney } = require('./serializers');

function buildQuotePdfBuffer(opts) {
  const businessName = (opts && opts.businessName) || 'Quote';
  const contactName = (opts && opts.contactName) || '';
  const contactEmail = (opts && opts.contactEmail) || '';
  const quote = (opts && opts.quote) || {};
  const breakdown = quote.breakdown || [];
  const accepted = !!(opts && opts.accepted);
  const acceptedAt = opts && opts.acceptedAt;

  return new Promise(function(resolve, reject) {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', function(c) { chunks.push(c); });
    doc.on('end', function() { resolve(Buffer.concat(chunks)); });
    doc.on('error', reject);

    doc.fontSize(22).font('Helvetica-Bold').text(businessName, { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(11).font('Helvetica').fillColor('#566').text('Online quote — ' + new Date().toLocaleDateString('en-AU'));
    doc.fillColor('#000');
    doc.moveDown(1);

    if (contactName || contactEmail) {
      doc.fontSize(12).font('Helvetica-Bold').text('Prepared for');
      doc.font('Helvetica').fontSize(11);
      if (contactName) doc.text(contactName);
      if (contactEmail) doc.text(contactEmail);
      doc.moveDown(0.8);
    }

    if (accepted) {
      doc.fillColor('#155c4a').font('Helvetica-Bold').fontSize(11)
        .text('ACCEPTED' + (acceptedAt ? (' — ' + new Date(acceptedAt).toLocaleString('en-AU')) : ''));
      doc.fillColor('#000').moveDown(0.8);
    }

    doc.fontSize(13).font('Helvetica-Bold').text('Itemised quote');
    doc.moveDown(0.4);
    doc.fontSize(10).font('Helvetica');

    breakdown.forEach(function(row) {
      const label = String(row.label || 'Item');
      const qty = row.quantity != null ? row.quantity : 1;
      const line = formatMoney(row.totalCents || 0);
      const detail = qty > 1 ? (label + '  ×' + qty) : label;
      doc.text(detail, { continued: true, width: 400 });
      doc.text(line, { align: 'right' });
    });

    doc.moveDown(0.6);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown(0.4);

    const subtotal = formatMoney(quote.subtotalCents || 0);
    const gst = formatMoney(quote.gstCents || 0);
    const total = formatMoney(quote.totalCents || 0);

    doc.font('Helvetica').text('Subtotal', { continued: true, width: 400 });
    doc.text(subtotal, { align: 'right' });
    doc.text('GST', { continued: true, width: 400 });
    doc.text(gst, { align: 'right' });
    doc.moveDown(0.2);
    doc.font('Helvetica-Bold').fontSize(12);
    doc.text('Total inc GST', { continued: true, width: 400 });
    doc.text(total, { align: 'right' });

    doc.moveDown(2);
    doc.fontSize(9).font('Helvetica').fillColor('#888')
      .text('This quote was generated by LeadPages Online Quote. Prices are indicative until confirmed by the business.', { align: 'center' });

    doc.end();
  });
}

module.exports = { buildQuotePdfBuffer };
