'use strict';

const IMAGE_PROVIDERS = Object.freeze({
  CLOUDINARY: 'cloudinary',
  PEXELS: 'pexels',
  AI: 'ai-images',
  PLACEHOLDER: 'placeholder',
  MOCK: 'mock'
});

const DEFAULT_PROVIDER_ORDER = Object.freeze([
  IMAGE_PROVIDERS.CLOUDINARY,
  IMAGE_PROVIDERS.PEXELS,
  IMAGE_PROVIDERS.AI,
  IMAGE_PROVIDERS.PLACEHOLDER
]);

module.exports = {
  IMAGE_PROVIDERS,
  DEFAULT_PROVIDER_ORDER,
  ENV_PEXELS_API_KEY: 'PEXELS_API_KEY',
  ENV_IMAGE_PROVIDER_DEFAULT: 'IMAGE_PROVIDER_DEFAULT',
  ENV_CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  ENV_CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  ENV_CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  ENV_CLOUDINARY_URL: 'CLOUDINARY_URL'
};
